import type { OpcodeFieldList } from '@/datatypes/opcode/body/list'

import { commentOf } from '../misc/comment-of'
import { fieldOf } from './field-of'

export function bodyOf(name: string, namespace: string, list: OpcodeFieldList) {
  let file = '// <auto-generated>'
  file += '\n\n'

  file += `namespace ${namespace};`

  file += '\n\n'
  file += commentOf('', 0)
  file += `public enum ${name} : byte`
  file += '\n'
  file += '{'
  file += '\n'

  file += list.map(e => fieldOf(e, 4)).join('\n\n')

  file += '\n'
  file += '}'
  file += '\n'

  return file
}
